name: Auto Deploy Voting App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:

    - name: Checkout Latest Code
      uses: actions/checkout@v4

    - name: Create Temp Deploy Folder
      run: |
        rm -rf /tmp/appdeploy
        mkdir -p /tmp/appdeploy

    - name: Copy Repository Files To Temp
      run: |
        rsync -av \
        --exclude='.git' \
        --exclude='.github' \
        --exclude='.env' \
        --exclude='node_modules' \
        --exclude='uploads' \
        --exclude='storage' \
        ./ /tmp/appdeploy/

    - name: Deploy Application
      run: |
        sudo rsync -av --delete \
        --exclude='.env' \
        --exclude='uploads' \
        --exclude='storage' \
        /tmp/appdeploy/ /var/www/html/

    - name: Set Permissions
      run: |
        sudo chown -R www-data:www-data /var/www/html
        sudo chmod -R 775 /var/www/html

    - name: Restart Apache2
      run: |
        sudo systemctl restart apache2

    - name: Verify Apache2
      run: |
        sudo systemctl status apache2 --no-pager
