name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy To Server
      run: |
        rsync -avz \
        -e "ssh -i ~/.ssh/mykey.pem -o StrictHostKeyChecking=no" \
        ./ ubuntu@98.81.219.151:/var/www/html/

    - name: Restart Apache
      run: |
        ssh -i ~/.ssh/mykey.pem -o StrictHostKeyChecking=no ubuntu@98.81.219.151 "
        sudo systemctl restart apache2
        "
