name: Auto Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:

    - name: Checkout Latest Code
      uses: actions/checkout@v4

    - name: Create Temp Folder
      run: |
        ssh -i ~/.ssh/mykey.pem -o StrictHostKeyChecking=no ubuntu@98.81.219.151 "
        mkdir -p /home/ubuntu/appdeploy
        "

    - name: Copy New Code Without Database Files
      run: |
        rsync -avz --delete \
        --exclude='.git' \
        --exclude='.github' \
        --exclude='.env' \
        --exclude='node_modules' \
        --exclude='storage' \
        --exclude='uploads' \
        --exclude='config/database.php' \
        -e "ssh -i ~/.ssh/mykey.pem -o StrictHostKeyChecking=no" \
        ./ ubuntu@98.81.219.151:/home/ubuntu/appdeploy/

    - name: Move Code To Web Server
      run: |
        ssh -i ~/.ssh/mykey.pem -o StrictHostKeyChecking=no ubuntu@98.81.219.151 "
        sudo rsync -av --delete \
        --exclude='.env' \
        --exclude='node_modules' \
        --exclude='storage' \
        --exclude='uploads' \
        --exclude='config/database.php' \
        /home/ubuntu/appdeploy/ /var/www/html/
        "

    - name: Set Permissions
      run: |
        ssh -i ~/.ssh/mykey.pem -o StrictHostKeyChecking=no ubuntu@98.81.219.151 "
        sudo chown -R www-data:www-data /var/www/html &&
        sudo chmod -R 775 /var/www/html
        "

    - name: Restart Apache2
      run: |
        ssh -i ~/.ssh/mykey.pem -o StrictHostKeyChecking=no ubuntu@98.81.219.151 "
        sudo systemctl restart apache2
        "
